version: '2'

services:
  gh2csv:
    build: .
    command: ["/bin/sh", "-c", "python /opt/github-issues-csv/main.py -u ${GITHUB_USER} -p ${GITHUB_PASSWORD} -r ${GITHUB_REPO} --no-quick > issues.csv > 2>&1"]
