version: '2'

services:
  gh2csv:
    build: .
    environment:
      - RUNTIME_GITHUB_USER=${ghuser}
      - RUNTIME_GITHUB_PASSWORD=${ghpassword}
      - RUNTIME_GITHUB_REPO=${repo}
    command: python main.py -u ${RUNTIME_GITHUB_USER} -p ${RUNTIME_GITHUB_PASSWORD} -r ${RUNTIME_GITHUB_REPO} --no-quick